/**
 ******************************************************************************
 * @file      sysmem.c
 * @author    Generated by STM32CubeIDE
 * @brief     STM32CubeIDE System Memory calls file
 *
 *            For more information about which C functions
 *            need which of these lowlevel functions
 *            please consult the newlib libc manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <errno.h>
#include <stdint.h>

/**
 * Pointer to the current high watermark of the heap usage
 */
static uint8_t *__sbrk_heap_end = NULL;

/**
 * @brief _sbrk() allocates memory to the newlib heap and is used by malloc
 *        and others from the C library
 *
 * @verbatim
 * ############################################################################
 * #  .data  #  .bss  #       newlib heap       #          MSP stack          #
 * #         #        #                         # Reserved by _Min_Stack_Size #
 * ############################################################################
 * ^-- RAM start      ^-- _end                             _estack, RAM end --^
 * @endverbatim
 *
 * This implementation starts allocating at the '_end' linker symbol
 * The '_Min_Stack_Size' linker symbol reserves a memory for the MSP stack
 * The implementation considers '_estack' linker symbol to be RAM end
 * NOTE: If the MSP stack, at any point during execution, grows larger than the
 * reserved size, please increase the '_Min_Stack_Size'.
 *
 * @param incr Memory size
 * @return Pointer to allocated memory
 */
void *_sbrk(ptrdiff_t incr)
{
  extern uint8_t _end; /* Symbol defined in the linker script */
  extern uint8_t _estack; /* Symbol defined in the linker script */
  extern uint32_t _Min_Stack_Size; /* Symbol defined in the linker script */
  const uint32_t stack_limit = (uint32_t)&_estack - (uint32_t)&_Min_Stack_Size;
  const uint8_t *max_heap = (uint8_t *)stack_limit;
  uint8_t *prev_heap_end;
  uintptr_t heap_min;
  uintptr_t heap_max;
  uintptr_t heap_end;
  uintptr_t next_heap_end;

  /* Initialize heap end at first call */
  if (NULL == __sbrk_heap_end)
  {
    __sbrk_heap_end = &_end;
  }

  heap_min = (uintptr_t)&_end;
  heap_max = (uintptr_t)max_heap;
  heap_end = (uintptr_t)__sbrk_heap_end;

  /*
   * Keep heap growth/shrink within [_end, stack_limit] and avoid pointer
   * arithmetic overflow/underflow on extreme incr values.
   */
  if (incr > 0)
  {
    uintptr_t inc = (uintptr_t)incr;
    if ((heap_end > heap_max) || (inc > (heap_max - heap_end)))
    {
      errno = ENOMEM;
      return (void *)-1;
    }
    next_heap_end = heap_end + inc;
  }
  else if (incr < 0)
  {
    /* Two's-complement absolute value without signed overflow on PTRDIFF_MIN */
    uintptr_t dec = (~(uintptr_t)incr) + 1u;
    if ((heap_end < heap_min) || (dec > (heap_end - heap_min)))
    {
      errno = ENOMEM;
      return (void *)-1;
    }
    next_heap_end = heap_end - dec;
  }
  else
  {
    next_heap_end = heap_end;
  }

  prev_heap_end = __sbrk_heap_end;
  __sbrk_heap_end = (uint8_t *)next_heap_end;

  return (void *)prev_heap_end;
}
